name: tezda_cart
description: "A one stop e-commerce platform"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.4
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
